interface WordPair {
    wordType: 'Basic' | 'Standard' | 'Advanced'; // You can define other types as needed
    pair1: string;
    pair2: string;
  }


  const wordPairs: WordPair[] = [
    {"wordType": "Basic", "pair1": "Cat", "pair2": "Dog"},
    {"wordType": "Basic", "pair1": "Sun", "pair2": "Moon"},
    {"wordType": "Basic", "pair1": "Apple", "pair2": "Banana"},
    {"wordType": "Basic", "pair1": "Car", "pair2": "Bike"},
    {"wordType": "Basic", "pair1": "House", "pair2": "Apartment"},
    {"wordType": "Basic", "pair1": "Book", "pair2": "Notebook"},
    {"wordType": "Basic", "pair1": "Chair", "pair2": "Table"},
    {"wordType": "Basic", "pair1": "Cup", "pair2": "Glass"},
    {"wordType": "Basic", "pair1": "Pen", "pair2": "Pencil"},
    {"wordType": "Basic", "pair1": "Tree", "pair2": "Plant"},
    {"wordType": "Basic", "pair1": "Flower", "pair2": "Petal"},
    {"wordType": "Basic", "pair1": "Fish", "pair2": "Shark"},
    {"wordType": "Basic", "pair1": "Bread", "pair2": "Butter"},
    {"wordType": "Basic", "pair1": "Knife", "pair2": "Fork"},
    {"wordType": "Basic", "pair1": "Window", "pair2": "Door"},
    {"wordType": "Basic", "pair1": "Mountain", "pair2": "Hill"},
    {"wordType": "Basic", "pair1": "Car", "pair2": "Truck"},
    {"wordType": "Basic", "pair1": "Phone", "pair2": "Tablet"},
    {"wordType": "Basic", "pair1": "Shoes", "pair2": "Socks"},
    {"wordType": "Basic", "pair1": "Pen", "pair2": "Marker"},
    {"wordType": "Basic", "pair1": "Bed", "pair2": "Pillow"},
    {"wordType": "Basic", "pair1": "Watch", "pair2": "Clock"},
    {"wordType": "Basic", "pair1": "Light", "pair2": "Dark"},
    {"wordType": "Basic", "pair1": "Window", "pair2": "Curtain"},
    {"wordType": "Basic", "pair1": "Computer", "pair2": "Laptop"},
    {"wordType": "Basic", "pair1": "Coffee", "pair2": "Tea"},
    {"wordType": "Basic", "pair1": "Bus", "pair2": "Train"},
    {"wordType": "Basic", "pair1": "Bird", "pair2": "Eagle"},
    {"wordType": "Basic", "pair1": "Ice", "pair2": "Fire"},
    {"wordType": "Basic", "pair1": "Salt", "pair2": "Pepper"},
    {"wordType": "Basic", "pair1": "Chocolate", "pair2": "Candy"},
    {"wordType": "Basic", "pair1": "Rice", "pair2": "Beans"},
    {"wordType": "Basic", "pair1": "Milk", "pair2": "Juice"},
    {"wordType": "Basic", "pair1": "Ocean", "pair2": "Sea"},
    {"wordType": "Basic", "pair1": "Paper", "pair2": "Scissors"},
    {"wordType": "Basic", "pair1": "Table", "pair2": "Chair"},
    {"wordType": "Basic", "pair1": "Shoe", "pair2": "Sandal"},
    {"wordType": "Basic", "pair1": "King", "pair2": "Queen"},
    {"wordType": "Basic", "pair1": "Bus", "pair2": "Car"},
    {"wordType": "Basic", "pair1": "Rain", "pair2": "Sunshine"},
    {"wordType": "Basic", "pair1": "Hot", "pair2": "Cold"},
    {"wordType": "Basic", "pair1": "Cat", "pair2": "Kitten"},
    {"wordType": "Basic", "pair1": "Dog", "pair2": "Puppy"},
    {"wordType": "Basic", "pair1": "Tree", "pair2": "Bush"},
    {"wordType": "Basic", "pair1": "Bird", "pair2": "Duck"},
    {"wordType": "Basic", "pair1": "Pen", "pair2": "Book"},
    {"wordType": "Basic", "pair1": "Ocean", "pair2": "Lake"},
    {"wordType": "Basic", "pair1": "Lion", "pair2": "Tiger"},
    {"wordType": "Basic", "pair1": "Tennis", "pair2": "Soccer"},
    {"wordType": "Basic", "pair1": "Socks", "pair2": "Shoes"},
    {"wordType": "Basic", "pair1": "Cup", "pair2": "Mug"},
    {"wordType": "Basic", "pair1": "Salt", "pair2": "Sugar"},
    {"wordType": "Standard", "pair1": "Ocean", "pair2": "Sea"},
    {"wordType": "Standard", "pair1": "School", "pair2": "University"},
    {"wordType": "Standard", "pair1": "Teacher", "pair2": "Professor"},
    {"wordType": "Standard", "pair1": "Doctor", "pair2": "Nurse"},
    {"wordType": "Standard", "pair1": "Computer", "pair2": "Smartphone"},
    {"wordType": "Standard", "pair1": "Train", "pair2": "Bus"},
    {"wordType": "Standard", "pair1": "Cat", "pair2": "Lion"},
    {"wordType": "Standard", "pair1": "Sun", "pair2": "Star"},
    {"wordType": "Standard", "pair1": "Chocolate", "pair2": "Vanilla"},
    {"wordType": "Standard", "pair1": "Fast", "pair2": "Quick"},
    {"wordType": "Standard", "pair1": "Night", "pair2": "Day"},
    {"wordType": "Standard", "pair1": "Plane", "pair2": "Helicopter"},
    {"wordType": "Standard", "pair1": "Piano", "pair2": "Guitar"},
    {"wordType": "Standard", "pair1": "Coffee", "pair2": "Espresso"},
    {"wordType": "Standard", "pair1": "Rain", "pair2": "Thunder"},
    {"wordType": "Standard", "pair1": "Moon", "pair2": "Planet"},
    {"wordType": "Standard", "pair1": "Football", "pair2": "Basketball"},
    {"wordType": "Standard", "pair1": "Window", "pair2": "Door"},
    {"wordType": "Standard", "pair1": "Cup", "pair2": "Glass"},
    {"wordType": "Standard", "pair1": "Bear", "pair2": "Tiger"},
    {"wordType": "Standard", "pair1": "Car", "pair2": "Bike"},
    {"wordType": "Standard", "pair1": "Pencil", "pair2": "Eraser"},
    {"wordType": "Standard", "pair1": "Rain", "pair2": "Cloud"},
    {"wordType": "Standard", "pair1": "Pen", "pair2": "Marker"},
    {"wordType": "Standard", "pair1": "Water", "pair2": "Fire"},
    {"wordType": "Standard", "pair1": "Hospital", "pair2": "Clinic"},
    {"wordType": "Standard", "pair1": "Cloud", "pair2": "Sky"},
    {"wordType": "Standard", "pair1": "Smartphone", "pair2": "Tablet"},
    {"wordType": "Standard", "pair1": "Morning", "pair2": "Evening"},
    {"wordType": "Standard", "pair1": "Green", "pair2": "Blue"},
    {"wordType": "Standard", "pair1": "Football", "pair2": "Baseball"},
    {"wordType": "Standard", "pair1": "Laptop", "pair2": "Desktop"},
    {"wordType": "Standard", "pair1": "Movie", "pair2": "Film"},
    {"wordType": "Standard", "pair1": "Apple", "pair2": "Orange"},
    {"wordType": "Standard", "pair1": "Butter", "pair2": "Jam"},
    {"wordType": "Standard", "pair1": "Guitar", "pair2": "Drums"},
    {"wordType": "Advanced", "pair1": "Alphabet", "pair2": "Character"},
    {"wordType": "Advanced", "pair1": "Mathematics", "pair2": "Physics"},
    {"wordType": "Advanced", "pair1": "History", "pair2": "Geography"},
    {"wordType": "Advanced", "pair1": "Physics", "pair2": "Astronomy"},
    {"wordType": "Advanced", "pair1": "Software", "pair2": "Hardware"},
    {"wordType": "Advanced", "pair1": "Economics", "pair2": "Commerce"},
    {"wordType": "Advanced", "pair1": "Literature", "pair2": "Poetry"},
    {"wordType": "Advanced", "pair1": "Cloud", "pair2": "Server"},
    {"wordType": "Advanced", "pair1": "Machine", "pair2": "Robot"},
    {"wordType": "Advanced", "pair1": "Artificial", "pair2": "Intelligence"},
    {"wordType": "Advanced", "pair1": "Robotics", "pair2": "Automation"},
    {"wordType": "Advanced", "pair1": "Blockchain", "pair2": "Cryptocurrency"},
    {"wordType": "Advanced", "pair1": "Data", "pair2": "Science"},
    {"wordType": "Advanced", "pair1": "Neural", "pair2": "Network"},
    {"wordType": "Advanced", "pair1": "Quantum", "pair2": "Physics"},
    {"wordType": "Advanced", "pair1": "Econometrics", "pair2": "Statistical"},
    {"wordType": "Advanced", "pair1": "Healthcare", "pair2": "Medicine"},
    {"wordType": "Advanced", "pair1": "Engineering", "pair2": "Technology"},
    {"wordType": "Advanced", "pair1": "Sustainability", "pair2": "Renewable"},
    {"wordType": "Advanced", "pair1": "Telecommunications", "pair2": "Networking"},
    {"wordType": "Advanced", "pair1": "Globalization", "pair2": "Localization"},
    {"wordType": "Advanced", "pair1": "Leadership", "pair2": "Management"},
    {"wordType": "Advanced", "pair1": "Entrepreneurship", "pair2": "Innovation"},
    {"wordType": "Advanced", "pair1": "Artificial", "pair2": "Technology"},
    {"wordType": "Advanced", "pair1": "Development", "pair2": "Programming"},
    {"wordType": "Advanced", "pair1": "Research", "pair2": "Analysis"}
];
  

export default wordPairs;
